nelmio_cors:
    defaults:
        origin_regex: true
        # This is the REACT server. Naturally one would have to change this for an appropriate website
        allow_origin: ['http://localhost:5000', 'http://localhost:3000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
