version: "3.4"

services:
    # MySql server
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
        restart: always
        command: --init-file /data/application/init.sql
        volumes:
            - ./database/.data/:/var/lib/mysql
            - ./database/init.sql:/data/application/init.sql
    # Synfony server
    server:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - "./back-end/:/symfony-and-react/back-end/"
            - /symfony-and-react/back-end/vendor
        ports:
            # synfony server is now available in localhost:8005
            - "0.0.0.0:8005:8000"
        links:
            - db
        # command: php /symfony-and-react/back-end/server/bin/console server:run 0.0.0.0:8000
    # React server
    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        volumes:
            - "./front-end/:/home/usr/symfony-and-react/front-end/"
            - /home/usr/symfony-and-react/front-end/node_modules
            - /home/usr/symfony-and-react/front-end/build
        ports:
            # react server is now available in localhost:5000
            - "0.0.0.0:5000:5000"
            # react development server is now available in localhost:5000
            - "0.0.0.0:3000:3000"
        links:
            - server
        command: bash -c "cd /home/usr/symfony-and-react/front-end/ && npm run serve"
